# Generated by Django 3.0.8 on 2020-08-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_additionalimage_bb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='content',
            field=models.TextField(default=0, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
